# 1. Exploración inicial del DataFrame

Lee el archivo nba.csv y responde:

1. ¿Qué representa este DataFrame?
2. Muestra los primeros cinco registros del DataFrame.
3.  Muestra cinco registros aleatorios.
4. Muestra los cinco últimos registros.

In [7]:
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
#2
df_nba=pd.read_csv('/content/drive/MyDrive/data/nba.csv')
df_nba.head(5) #primeros 5

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [8]:
#3
df_nba.sample(5) #5 aleatorio

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
294,LaMarcus Aldridge,San Antonio Spurs,12.0,PF,30.0,6-11,240.0,Texas,19689000.0
326,Jorge Gutierrez,Charlotte Hornets,12.0,PG,27.0,6-3,189.0,California,189455.0
366,Nikola Vucevic,Orlando Magic,9.0,C,25.0,7-0,260.0,USC,11250000.0
237,Zaza Pachulia,Dallas Mavericks,27.0,C,32.0,6-11,275.0,NaN,5200000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0

In [9]:
#4
df_nba.tail(5) #últimos 5

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 2. Análisis de columnas y tipos de datos

1. ¿Qué columnas contiene el DataFrame?
2. ¿Qué tipo de dato tiene cada columna?
3. ¿La columna de altura (height) está en el tipo correcto?

In [10]:
#1
df_nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    object
 6   Weight    457 non-null    float64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

2. Los tipos de datos en cada columna son:
* Name: cadena de texto (object)
* Team: cadena de texto (object)
* Number: número decimal (float64)
* Position: cadena de texto (object)
* Age: número decimal (float64)
* Height: cadena de texto (object)
* Weight: número decimal (float64)
* College: cadena de texto (object)
* Salary: número decimal (float64)

3. La columna `height`no esta en el tipo correcto, ya que es una columna que contiene valores numéricos pero se registra como cadena de texto por que presenta un guión (`-`) el cual se ha de cambiar para transformar esta columna a la adecuada

In [11]:
#Para cambiar el tipo de columna
df_nba['Height'] = df_nba['Height'].str.replace("-", ".").astype(float) #esto es para cambiar, pero no me funciona pq de alguna manera lo cambie antes
df_nba['Height']

0      6.2
1      6.6
2      6.5
3      6.5
4      6.1
      ...
453    6.3
454    6.1
455    7.3
456    7.0
457    NaN
Name: Height, Length: 458, dtype: float64

In [12]:
df_nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    float64
 6   Weight    457 non-null    float64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(5), object(4)
memory usage: 32.3+ KB

#3. Valores nulos

1. ¿Qué columnas tienen valores nulos?
2. ¿En cuáles los valores nulos tienen sentido y en cuáles representan datos faltantes?

In [13]:
#1
df_nba.isnull().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

2. Valores nulos con sentido:
* College: no todos los jugadores han ido a la universidad, pueden venir de ligas internacionales o directamente de bachillerato o equivalente
* Salario: no todos los salarios de los jugadores son púiblicos

Valores nulos que representan datos faltantes:
* Nombre, Team, Age, Position, Height y Weight: sin embargo al realizar un previo analisis de la base de datos, se observa que existe una columna incompleta al final de la tabla

# 4. Estadísticas básicas

1. ¿Cuál es la media y la mediana de los salarios?
2. ¿Cuál es el mínimo y el máximo de la altura de los jugadores?

In [14]:
#1
print(f"media: {df_nba['Salary'].mean()}")
print(f"mediana: {df_nba['Salary'].median()}")

media: 4842684.105381166
mediana: 2839073.0

In [15]:
#2_Salario máximo
df_nba[df_nba['Salary']==df_nba['Salary'].max()]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
109,Kobe Bryant,Los Angeles Lakers,24.0,SF,37.0,6.6,212.0,NaN,25000000.0

In [16]:
#2_Salario mínimo
df_nba[df_nba['Salary']==df_nba['Salary'].min()]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
32,Thanasis Antetokounmpo,New York Knicks,43.0,SF,23.0,6.7,205.0,NaN,30888.0

#5. Indexación y consulta por nombre

1. Establece el nombre de los jugadores como índice del DataFrame.
2. Busca toda la información disponible sobre Metta World Peace.

In [17]:
#1
df_nba= df_nba.set_index('Name')
df_nba

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Avery Bradley,Boston Celtics,0.0,PG,25.0,6.2,180.0,Texas,7730337.0
Jae Crowder,Boston Celtics,99.0,SF,25.0,6.6,235.0,Marquette,6796117.0
John Holland,Boston Celtics,30.0,SG,27.0,6.5,205.0,Boston University,NaN
R.J. Hunter,Boston Celtics,28.0,SG,22.0,6.5,185.0,Georgia State,1148640.0
Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6.1,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...
Shelvin Mack,Utah Jazz,8.0,PG,26.0,6.3,203.0,Butler,2433333.0
Raul Neto,Utah Jazz,25.0,PG,24.0,6.1,179.0,NaN,900000.0
Tibor Pleiss,Utah Jazz,21.0,C,26.0,7.3,256.0,NaN,2900000.0
Jeff Withey,Utah Jazz,24.0,C,26.0,7.0,231.0,Kansas,947276.0
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
#2
df_nba.loc['Metta World Peace']

Team        Los Angeles Lakers
Number                    37.0
Position                    SF
Age                       36.0
Height                     6.7
Weight                   260.0
College             St. John's
Salary                947276.0
Name: Metta World Peace, dtype: object

#6. Filtrado de datos

1. Encuentra a los jugadores que cobran más de un millón de dólares. Usa una mask
2. Encuentra a los bases (position) de los Lakers.
3. Encuentra a los jugadores que estudiaron en Texas y juegan actualmente en Texas.

In [19]:
#1
mask_salario = df_nba['Salary'] >=1000000
df_salario=df_nba[mask_salario]
df_salario

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Avery Bradley,Boston Celtics,0.0,PG,25.0,6.2,180.0,Texas,7730337.0
Jae Crowder,Boston Celtics,99.0,SF,25.0,6.6,235.0,Marquette,6796117.0
R.J. Hunter,Boston Celtics,28.0,SG,22.0,6.5,185.0,Georgia State,1148640.0
Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6.1,231.0,NaN,5000000.0
Amir Johnson,Boston Celtics,90.0,PF,29.0,6.9,240.0,NaN,12000000.0
...,...,...,...,...,...,...,...,...
Rodney Hood,Utah Jazz,5.0,SG,23.0,6.8,206.0,Duke,1348440.0
Joe Ingles,Utah Jazz,2.0,SF,28.0,6.8,226.0,NaN,2050000.0
Trey Lyles,Utah Jazz,41.0,PF,20.0,6.1,234.0,Kentucky,2239800.0
Shelvin Mack,Utah Jazz,8.0,PG,26.0,6.3,203.0,Butler,2433333.0
Tibor Pleiss,Utah Jazz,21.0,C,26.0,7.3,256.0,NaN,2900000.0

In [20]:
#2
PG = (df_nba['Position'] == 'PG') & (df_nba['Team'] == 'Los Angeles Lakers')
df_nba[PG]

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Jordan Clarkson,Los Angeles Lakers,6.0,PG,24.0,6.5,194.0,Missouri,845059.0
Marcelo Huertas,Los Angeles Lakers,9.0,PG,33.0,6.3,200.0,NaN,525093.0
D'Angelo Russell,Los Angeles Lakers,1.0,PG,20.0,6.5,195.0,Ohio State,5103120.0

In [21]:
#3
nba_texas = (df_nba ['College'].isin(['Texas', 'Texas A&M', 'Bylor', 'Houston'])) & ( (df_nba ['Team'] == 'Dallas Mavericks') | (df_nba ['Team'] == 'Houston Rockets') | (df_nba ['Team'] == 'San Antonio Spurs'))
df_nba[nba_texas]

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
LaMarcus Aldridge,San Antonio Spurs,12.0,PF,30.0,6.11,240.0,Texas,19689000.0
Jonathon Simmons,San Antonio Spurs,17.0,SG,26.0,6.60,195.0,Houston,525093.0

#7. Ordenación y rankings

1. Ordena a los jugadores de menor a mayor salario.
2. ¿Quiénes son los cinco jugadores peor pagados de la liga?
3. ¿Quiénes son los cinco jugadores mejor pagados de la liga?

In [22]:
#1
df_nba.sort_values('Salary', ascending=True)

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Thanasis Antetokounmpo,New York Knicks,43.0,SF,23.0,6.70,205.0,NaN,30888.0
Orlando Johnson,New Orleans Pelicans,0.0,SG,27.0,6.50,220.0,UC Santa Barbara,55722.0
Phil Pressey,Phoenix Suns,25.0,PG,25.0,5.11,175.0,Missouri,55722.0
Alan Williams,Phoenix Suns,15.0,C,23.0,6.80,260.0,UC Santa Barbara,83397.0
Jordan McRae,Cleveland Cavaliers,12.0,SG,25.0,6.50,179.0,Tennessee,111196.0
...,...,...,...,...,...,...,...,...
Briante Weber,Miami Heat,12.0,PG,23.0,6.20,165.0,Virginia Commonwealth,NaN
Dorell Wright,Miami Heat,11.0,SF,30.0,6.90,205.0,NaN,NaN
Axel Toupane,Denver Nuggets,6.0,SG,23.0,6.70,210.0,NaN,NaN
Greg Smith,Minnesota Timberwolves,4.0,PF,25.0,6.10,250.0,Fresno State,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
#2
df_nba.sort_values('Salary', ascending=True).head(5)

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Thanasis Antetokounmpo,New York Knicks,43.0,SF,23.0,6.70,205.0,NaN,30888.0
Orlando Johnson,New Orleans Pelicans,0.0,SG,27.0,6.50,220.0,UC Santa Barbara,55722.0
Phil Pressey,Phoenix Suns,25.0,PG,25.0,5.11,175.0,Missouri,55722.0
Alan Williams,Phoenix Suns,15.0,C,23.0,6.80,260.0,UC Santa Barbara,83397.0
Jordan McRae,Cleveland Cavaliers,12.0,SG,25.0,6.50,179.0,Tennessee,111196.0

In [24]:
#3
df_nba.sort_values('Salary', ascending=False).head(5)

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Kobe Bryant,Los Angeles Lakers,24.0,SF,37.0,6.60,212.0,NaN,25000000.0
LeBron James,Cleveland Cavaliers,23.0,SF,31.0,6.80,250.0,NaN,22970500.0
Carmelo Anthony,New York Knicks,7.0,SF,32.0,6.80,240.0,Syracuse,22875000.0
Dwight Howard,Houston Rockets,12.0,C,30.0,6.11,265.0,NaN,22359364.0
Chris Bosh,Miami Heat,1.0,PF,32.0,6.11,235.0,Georgia Tech,22192730.0

#8. Análisis por equipo y posición

1. ¿Cuáles son los cinco equipos con menor altura media?
2. ¿Cuáles son los cinco equipos con mayor masa salarial?
3. Ordena las posiciones por salario medio:
4. ¿En qué posición de la NBA es más rentable jugar?

In [26]:
#1
df_nba.groupby('Team')['Height'].mean().sort_values(ascending=True).head(5)

Team
Brooklyn Nets             6.348000
Indiana Pacers            6.369333
Memphis Grizzlies         6.422222
Minnesota Timberwolves    6.423571
Oklahoma City Thunder     6.434000
Name: Height, dtype: float64

In [28]:
#2
df_nba.groupby('Team')['Salary'].sum().sort_values(ascending=False).head(5)

Team
Cleveland Cavaliers      106988689.0
Los Angeles Clippers      94854640.0
Oklahoma City Thunder     93765298.0
Golden State Warriors     88868997.0
Chicago Bulls             86783378.0
Name: Salary, dtype: float64

In [30]:
#3
df=df_nba.groupby('Position')['Salary'].mean().sort_values(ascending=False).head(5)
df

Position
C     5.967052e+06
PG    5.077829e+06
SF    4.857393e+06
PF    4.562483e+06
SG    4.009861e+06
Name: Salary, dtype: float64

4. La posición más rentable es central `C`